name: burp-suite
base: core22
version: '2023.10.3.6'
summary: Vulnerability scanning, penetration testing, and security platform.
description: |
  Burp Suite is a software security application used for penetration testing
  of web applications. Both a free and a paid version of the software are
  available. The software is developed by the company PortSwigger.

grade: stable
confinement: strict

environment:
  _JAVA_OPTIONS: -Duser.home="$SNAP_USER_DATA"

apps:
  burp-suite:
    command: /opt/BurpSuiteCommunity/BurpSuiteCommunity
    plugs:
      - network
      - network-bind
      - system-observe
      - x11

plugs:
  dot-config-burp-suite:
    interface: personal-files
    write:
      - $HOME/.BurpSuite
  etc-hosts:
    interface: system-files
    read:
      - /etc/hosts
      - /etc/host.conf

parts:
  burp-suite:
    plugin: nil
    override-build: |
      snapcraftctl build
      wget "https://portswigger-cdn.net/burp/releases/download?product=community&version=${SNAPCRAFT_PROJECT_VERSION}&type=Linux" -O install.sh
      echo -e "\n/opt/BurpSuiteCommunity\nn\n" > /tmp/input
      sh ./install.sh -c < /tmp/input
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt
      cp -rp /opt/BurpSuiteCommunity $SNAPCRAFT_PART_INSTALL/opt/
    build-packages:
      - libfreetype6-dev
      - wget
    stage-packages:
      - libasound2
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libcairo2
      - libcups2
      - libgbm1
      - libnss3
      - libpango-1.0-0
      - libxcb1
      - libxcomposite1
      - libxdamage1
      - libxext6
      - libxfixes3
      - libxkbcommon0
      - libxrandr2
      - libxtst6
      - openjdk-18-jre-headless
      - util-linux
